pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: '$(dockerId)/gomemes:$(build.buildId)'

steps:
- script: |
    docker build -f Dockerfile -t $(imageName) .
    docker login -u $(dockerId) -p $pswd
    docker push $(imageName)
  env:
    pswd: $(dockerPassword)